package net.frogmouth.rnd.jim.s4676.trackpoint;

/**
 * Track Point process type.
 *
 * <p>Indicator whether a track point was generated by or modified by a human or an algorithm.
 */
public interface IProcessType {}
