package net.frogmouth.rnd.jim.s4676.tracker;

/**
 * The type of tracker.
 *
 * <p>Indicates whether a track was generated by a human, algorithm, or combination of the two.
 */
public interface ITrackerType {}
