package net.frogmouth.rnd.jim.s4676.tracker;

/**
 * The type of tracker.
 *
 * <p>Indicates whether a track was generated by a human, algorithm, or combination of the two.
 */
public enum TrackerType implements ITrackerType {
    /**
     * Manual Tracker.
     *
     * <p>Indicates a tracker that generates tracks via direct human input.
     */
    MANUAL_TRACKER,

    /**
     * Automatic Tracker.
     *
     * <p>Indicates a tracker that generates tracks via an automated algorithm.
     */
    AUTOMATIC_TRACKER,

    /**
     * Semi-automated tracker.
     *
     * <p>Indicates a tracker that generates tracks via a combination of human input and an
     * automated algorithm.
     */
    SEMIAUTOMATIC_TRACKER
}
